name: "tagged-release"

on:
  push:
    tags:
      - "v*"
      - "!v*-*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: "Prepare release"
        run: |
          ls -la
          chmod +x .github/prepare-release.sh
          ./.github/prepare-release.sh
          ls -la bin
          
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: | 
            bin/*