name: "tagged-release"

on:
  push:
    branches:
      - "dev"
    tags:
      - "v*-dev"

permissions: write-all


jobs:
  tagged-release:
    if: contains(github.event.head_commit.message, 'Release:')
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: "Prepare release"
        run: |
          ls -la
          chmod +x .github/prepare-release.sh
          ./.github/prepare-release.sh
          ls -la bin

      - name: "Prepare notes"
        run: |
          BASE_SHA=$(git rev-parse $GITHUB_BASE_REF)
          HEAD_SHA=$(git rev-parse HEAD)
          echo "$GITHUB_BASE_REF"
          echo "Base SHA: $BASE_SHA"
          echo "Head SHA: $HEAD_SHA"

          mkdir tmp
          chmod +x .github/prepare-notes.sh
          ./.github/prepare-notes.sh $GITHUB_BASE_REF

      - name: "Create release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              -d \
              -F 'tmp/notes.md' \
              --generate-notes \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              ./bin/*